### PR TITLE
Merge similar-behaving `read_(rarity)` functions

### PR DESCRIPTION
**Pull request by SDSkyKlouD**
#### Summary
I found some functions which have almost same process. [DRY<sup>Don't Repeat Yourself</sup>](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) code design pattern will make the codes cleaner. I will create more pull requests whenever I found repeated codes! :P

### CODE REVIEW

**Comment by Expugn** [comment]
Looks good! Thanks for cleaning up my messy code, heh.

**Comment by SDSkyKlouD** [comment]
It's my pleasure!
If I may say so, would you mind add me as a collaborator of this repository? I hope improve the code quality of this project on my free time, without time-spending pull-requesting. (and Korean translations too!! XD)
If this made you feel bad, please forgive me. :cry:

**Comment by Expugn** [comment]
i dont mind, you should have the invite link sent somewhere.

**Comment by SDSkyKlouD** [comment]
You mean e-mail address or something? I just got invitation in GitHub and accepted. If you still need e-mail address or something, please let me know!
Anyway thank you adding me as a collaborator! Is there anything to mind?

**Comment by Expugn** [comment]
no, i dont think i need an email if you were able to accept it.

as for things to mind, i dont really have anything at the moment. just don't break things, heh.

**Comment by SDSkyKlouD** [comment]
Sure thing XD thank you again!

**Pull request merged**
