### PR TITLE
Update Korean & Japanese translations

### PR DESCRIPTION
**Pull request by SDSkyKlouD**
#### Summary
Korean and Japanese translations for new strings ;)

### CODE REVIEW

**Comment by Expugn** [comment]
thanks as always!

**Comment by Expugn** [comment]
ah by the way, you're missing:
`toasts.project_completed` for `ko.json` and `ja.json`
if that wasn't intentional.

**Comment by SDSkyKlouD** [comment]
OH MY GOD so sorry for missing X(
  
ko : `프로젝트 \"${project_name}\"가 완료되었습니다!`
ja : `プロジェクト\"${project_name}\"は完了されました！`
  
@Expugn, can you apply this translations for me? ~~It's so shameful to open a new pull request~~ T.T

**Comment by Expugn** [comment]
haha, no worries. added the text.

**Pull request merged**
